### ISSUE TITLE
Your comment on chris-chris repo disappeared

### ISSUE THREAD

**Issue by Seraphli** [simonmeister/pysc2-rl-agents#1]
I don't whether he deleted your comment or you deleted it. If he deleted that, well shame on him. Still, I saw the comment through email notification. The code looks nice. Maybe I will try it when I have a free time.

**Comment by simonmeister** [comment]
I deleted it as i thought it may be too much self advertisement :) Though it can be hard to make people note the repository, so i may add it again. Thanks!
