### ISSUE TITLE
'train'-folder does not exists - fails to run on Windows 10

### ISSUE THREAD

**Issue by brean** [simonmeister/pysc2-rl-agents#2]
you need to create the output folder (or add it manually with a .gitkeep-file) or it fails with: "out/summary\my_experiment\train; No such file or directory"

**Comment by danielpalen** [comment]
This was actually a bug which occurred because we hardcoded the default path to `out/summary` which works find for Mac and Linux but on Windows this is not a valid path.

It is fixed now. The directories should be created automatically if they do not exist.
